create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 1 and 320),
  message text not null check (char_length(message) between 1 and 5000),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Public visitors may submit messages, but only the server's secret key can
-- read them. Never expose SUPABASE_SECRET_KEY in browser code.
revoke all on table public.messages from anon, authenticated;
grant insert (name, email, message) on table public.messages to anon;
