import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#e58958",
        "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
        "tertiary-fixed-dim": "#f3f0eb",
        "on-error-container": "#ffd2c8",
        "on-tertiary-fixed-variant": "#6e6d69",
        "surface-container-highest": "rgb(var(--c-surface-container-highest) / <alpha-value>)",
        "on-tertiary-fixed": "#51504d",
        "on-secondary-fixed-variant": "#972800",
        "on-tertiary": "#605f5b",
        "secondary": "#ff7348",
        "on-primary-container": "#3f1600",
        "secondary-fixed": "#ffc4b3",
        "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
        "outline": "rgb(var(--c-outline) / <alpha-value>)",
        "primary-fixed": "#f59663",
        "error": "#ff7351",
        "on-tertiary-container": "#575753",
        "tertiary": "rgb(var(--c-tertiary) / <alpha-value>)",
        "secondary-dim": "#ff7348",
        "surface-tint": "#f59663",
        "surface-bright": "rgb(var(--c-surface-bright) / <alpha-value>)",
        "on-primary-fixed-variant": "#602600",
        "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "on-primary": "#521f00",
        "tertiary-container": "#eeebe6",
        "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "on-secondary-fixed": "#651800",
        "secondary-container": "#a12e05",
        "primary": "#f59663",
        "inverse-primary": "#954a1e",
        "on-secondary-container": "#ffe6df",
        "surface": "rgb(var(--c-surface) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-secondary": "#420d00",
        "error-dim": "#d53d18",
        "inverse-surface": "rgb(var(--c-inverse-surface) / <alpha-value>)",
        "secondary-fixed-dim": "#ffb19a",
        "tertiary-dim": "#eeebe6",
        "surface-container-lowest": "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
        "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
        "on-error": "#450900",
        "error-container": "#b92902",
        "background": "rgb(var(--c-background) / <alpha-value>)",
        "surface-container-high": "rgb(var(--c-surface-container-high) / <alpha-value>)",
        "on-background": "rgb(var(--c-on-background) / <alpha-value>)",
        "primary-fixed-dim": "#e58958",
        "tertiary-fixed": "#ffffff",
        "primary-dim": "#e58958",
        "inverse-on-surface": "rgb(var(--c-inverse-on-surface) / <alpha-value>)"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
};
export default config;
